FROM docker.io/bitnami/airflow:2

USER root
RUN apt-get update
RUN apt-get update && apt-get install -y build-essential libpq-dev
RUN pip install psycopg2-binary apache-airflow apache-airflow-providers-apache-spark
USER 1001
